del "Global\ccInit.lua"
del "Global\ccItemSorter.lua" 
del "Global\ccConvenience.lua" 
del "Global\ccInfo.lua" 
del "Global\ccCombatlog.lua"
del "Global\ccBuffExpirationAlert.lua"
del "Global\ccCombatlogParser.lua"
del "Global\ccAutoRepair.lua"
del "Global\ccTravelSchedule.lua"
del "Global\ccTrainingDummy.lua"
del "Global\ccSpellsInfo.lua"
del "Global\ccUtils.lua"
del "Global\ccSkillTooltips.lua"

del "ccUninst.bat"

